language: python
cache: pip
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
before_install:
- pip install pytest pytest-cov python-coveralls
install: "pip install -r requirements.txt"
# command to run tests
#before_script: nosetests
script:
- nosetests
#- py.test --cov=espandas
#after_success: coveralls
